var ItemType =
{
	Scroll : 0,
	Bangle : 1,
	Grass : 2,
	Amulet : 3,
	Jar : 4,
	Cane : 5
}

var DataBase = 
[
	// 巻物
	{ type:ItemType.Scroll,		name:'紹介状',				price:{buy:10,		sell:3} },
	{ type:ItemType.Scroll,		name:'脱出の巻物',			price:{buy:100,		sell:35} },
	{ type:ItemType.Scroll,		name:'あかりの巻物',		price:{buy:100,		sell:35} },
	{ type:ItemType.Scroll,		name:'識別の巻物',			price:{buy:300,		sell:105} },
	{ type:ItemType.Scroll,		name:'おはらいの巻物',		price:{buy:500,		sell:175} },
	{ type:ItemType.Scroll,		name:'天の恵みの巻物',		price:{buy:500,		sell:175} },
	{ type:ItemType.Scroll,		name:'地の恵みの巻物',		price:{buy:500,		sell:175} },
	{ type:ItemType.Scroll,		name:'メッキの巻物',		price:{buy:500,		sell:175} },
	{ type:ItemType.Scroll,		name:'タグの巻物',			price:{buy:500,		sell:175} },
	{ type:ItemType.Scroll,		name:'吸出しの巻物',		price:{buy:500,		sell:175} },
	{ type:ItemType.Scroll,		name:'壺増大の巻物',		price:{buy:500,		sell:175} },
	{ type:ItemType.Scroll,		name:'バナナの巻物',		price:{buy:500,		sell:175} },
	{ type:ItemType.Scroll,		name:'ゾワゾワの巻物',		price:{buy:800,		sell:280} },
	{ type:ItemType.Scroll,		name:'与薬の巻物',			price:{buy:800,		sell:280} },
	{ type:ItemType.Scroll,		name:'水がれの巻物',		price:{buy:800,		sell:280} },
	{ type:ItemType.Scroll,		name:'ワナ消しの巻物',		price:{buy:800,		sell:280} },
	{ type:ItemType.Scroll,		name:'ワナの巻物',			price:{buy:800,		sell:280} },
	{ type:ItemType.Scroll,		name:'拾えずの巻物',		price:{buy:800,		sell:280} },
	{ type:ItemType.Scroll,		name:'ひきよせの巻物',		price:{buy:800,		sell:280} },
	{ type:ItemType.Scroll,		name:'くちなしの巻物',		price:{buy:800,		sell:280} },
	{ type:ItemType.Scroll,		name:'バクスイの巻物',		price:{buy:1000,	sell:350} },
	{ type:ItemType.Scroll,		name:'混乱の巻物',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Scroll,		name:'真空斬りの巻物',		price:{buy:1000,	sell:350} },
	{ type:ItemType.Scroll,		name:'困った時の巻物',		price:{buy:1000,	sell:350} },
	{ type:ItemType.Scroll,		name:'技回復の巻物',		price:{buy:1000,	sell:350} },
	{ type:ItemType.Scroll,		name:'オーラ消しの巻物',	price:{buy:1000,	sell:350} },
	{ type:ItemType.Scroll,		name:'魔物部屋の巻物',		price:{buy:1000,	sell:350} },
	{ type:ItemType.Scroll,		name:'敵加速の巻物',		price:{buy:1000,	sell:350} },
	{ type:ItemType.Scroll,		name:'昼夜の巻物',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Scroll,		name:'迷子の巻物',			price:{buy:3000,	sell:1050} },
	{ type:ItemType.Scroll,		name:'聖域の巻物',			price:{buy:3000,	sell:1050} },
	{ type:ItemType.Scroll,		name:'全滅の巻物',			price:{buy:3000,	sell:1050} },
	{ type:ItemType.Scroll,		name:'白紙の巻物',			price:{buy:5000,	sell:1750} },
	{ type:ItemType.Scroll,		name:'ねだやしの巻物',		price:{buy:10000,	sell:3500} },
	{ type:ItemType.Scroll,		name:'いかすしの巻物',		price:{buy:200,		sell:70} },
	{ type:ItemType.Scroll,		name:'ぬれた巻物',			price:{buy:10,		sell:3} },
	{ type:ItemType.Scroll,		name:'ただの紙切れ',		price:{buy:10,		sell:3} },
	// 腕輪
	{ type:ItemType.Bangle,		name:'遠投の腕輪',			price:{buy:2000,	sell:700} },
	{ type:ItemType.Bangle,		name:'ちからの腕輪',		price:{buy:2000,	sell:700} },
	{ type:ItemType.Bangle,		name:'ヘタ投げの腕輪',		price:{buy:2000,	sell:700} },
	{ type:ItemType.Bangle,		name:'混乱よけの腕輪',		price:{buy:3000,	sell:1050} },
	{ type:ItemType.Bangle,		name:'呪いよけの腕輪',		price:{buy:3000,	sell:1050} },
	{ type:ItemType.Bangle,		name:'睡眠よけの腕輪',		price:{buy:3000,	sell:1050} },
	{ type:ItemType.Bangle,		name:'毒消しの腕輪',		price:{buy:3000,	sell:1050} },
	{ type:ItemType.Bangle,		name:'保持の腕輪',			price:{buy:3000,	sell:1050} },
	{ type:ItemType.Bangle,		name:'ワナの腕輪',			price:{buy:3000,	sell:1050} },
	{ type:ItemType.Bangle,		name:'痛恨の腕輪',			price:{buy:3000,	sell:1050} },
	{ type:ItemType.Bangle,		name:'魔物呼びの腕輪',		price:{buy:3000,	sell:1050} },
	{ type:ItemType.Bangle,		name:'回復の腕輪',			price:{buy:5000,	sell:1750} },
	{ type:ItemType.Bangle,		name:'水グモの腕輪',		price:{buy:5000,	sell:1750} },
	{ type:ItemType.Bangle,		name:'壁抜けの腕輪',		price:{buy:5000,	sell:1750} },
	{ type:ItemType.Bangle,		name:'裏道の腕輪',			price:{buy:5000,	sell:1750} },
	{ type:ItemType.Bangle,		name:'高飛びの腕輪',		price:{buy:5000,	sell:1750} },
	{ type:ItemType.Bangle,		name:'爆発の腕輪',			price:{buy:5000,	sell:1750} },
	{ type:ItemType.Bangle,		name:'気配察知の腕輪',		price:{buy:5000,	sell:1750} },
	{ type:ItemType.Bangle,		name:'道具感知の腕輪',		price:{buy:5000,	sell:1750} },
	{ type:ItemType.Bangle,		name:'弾きよけの腕輪',		price:{buy:10000,	sell:3500} },
	{ type:ItemType.Bangle,		name:'しあわせの腕輪',		price:{buy:10000,	sell:3500} },
	{ type:ItemType.Bangle,		name:'鑑定師の腕輪',		price:{buy:30000,	sell:10500} },
	{ type:ItemType.Bangle,		name:'透視の腕輪',			price:{buy:30000,	sell:10500} },
	{ type:ItemType.Bangle,		name:'ワナ師の腕輪',		price:{buy:30000,	sell:10500} },
	{ type:ItemType.Bangle,		name:'ブルドッ君の腕輪',	price:{buy:30000,	sell:10500} },
	// 草
	{ type:ItemType.Grass,		name:'雑草',				price:{buy:10,		sell:3} },
	{ type:ItemType.Grass,		name:'薬草',				price:{buy:50,		sell:17} },
	{ type:ItemType.Grass,		name:'弟切草',				price:{buy:100,		sell:35} },
	{ type:ItemType.Grass,		name:'毒消し草',			price:{buy:100,		sell:35} },
	{ type:ItemType.Grass,		name:'毒草',				price:{buy:100,		sell:35} },
	{ type:ItemType.Grass,		name:'高飛び草',			price:{buy:100,		sell:35} },
	{ type:ItemType.Grass,		name:'いやし草',			price:{buy:200,		sell:70} },
	{ type:ItemType.Grass,		name:'胃拡張の種',			price:{buy:300,		sell:105} },
	{ type:ItemType.Grass,		name:'胃縮小の種',			price:{buy:300,		sell:105} },
	{ type:ItemType.Grass,		name:'すばやさ草',			price:{buy:300,		sell:105} },
	{ type:ItemType.Grass,		name:'混乱草',				price:{buy:300,		sell:105} },
	{ type:ItemType.Grass,		name:'めぐすり草',			price:{buy:300,		sell:105} },
	{ type:ItemType.Grass,		name:'パワーアップ草',		price:{buy:300,		sell:105} },
	{ type:ItemType.Grass,		name:'成長の種',			price:{buy:300,		sell:105} },
	{ type:ItemType.Grass,		name:'目つぶし草',			price:{buy:300,		sell:105} },
	{ type:ItemType.Grass,		name:'命の草',				price:{buy:500,		sell:175} },
	{ type:ItemType.Grass,		name:'ちからの草',			price:{buy:500,		sell:175} },
	{ type:ItemType.Grass,		name:'睡眠草',				price:{buy:500,		sell:175} },
	{ type:ItemType.Grass,		name:'狂戦士の種',			price:{buy:500,		sell:175} },
	{ type:ItemType.Grass,		name:'ドラゴン草',			price:{buy:500,		sell:175} },
	{ type:ItemType.Grass,		name:'復活の草',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Grass,		name:'やりなおし草',		price:{buy:1500,	sell:525} },
	{ type:ItemType.Grass,		name:'しあわせ草',			price:{buy:2000,	sell:700} },
	{ type:ItemType.Grass,		name:'不幸の種',			price:{buy:2000,	sell:700} },
	{ type:ItemType.Grass,		name:'物忘れの草',			price:{buy:2000,	sell:700} },
	{ type:ItemType.Grass,		name:'無敵草',				price:{buy:2000,	sell:700} },
	{ type:ItemType.Grass,		name:'忌火起草',			price:{buy:2000,	sell:700} },
	{ type:ItemType.Grass,		name:'天使の種',			price:{buy:5000,	sell:1750} },
	{ type:ItemType.Grass,		name:'超不幸の種',			price:{buy:5000,	sell:1750} },
	// 札
	{ type:ItemType.Amulet,		name:'睡眠の札',			price:{buy:500,		sell:175} },
	{ type:ItemType.Amulet,		name:'封印の札',			price:{buy:500,		sell:175} },
	{ type:ItemType.Amulet,		name:'混乱の札',			price:{buy:500,		sell:175} },
	{ type:ItemType.Amulet,		name:'空振りの札',			price:{buy:500,		sell:175} },
	{ type:ItemType.Amulet,		name:'ゾワゾワの札',		price:{buy:500,		sell:175} },
	{ type:ItemType.Amulet,		name:'影縫いの札',			price:{buy:500,		sell:175} },
	{ type:ItemType.Amulet,		name:'加速の札',			price:{buy:500,		sell:175} },
	{ type:ItemType.Amulet,		name:'鈍足の札',			price:{buy:500,		sell:175} },
	{ type:ItemType.Amulet,		name:'狂戦士の札',			price:{buy:500,		sell:175} },
	{ type:ItemType.Amulet,		name:'イカリの札',			price:{buy:500,		sell:175} },
	{ type:ItemType.Amulet,		name:'オオイカリの札',		price:{buy:500,		sell:175} },
	// 壺
	{ type:ItemType.Jar,		name:'保存の壺',			price:{buy:600,		sell:210} },
	{ type:ItemType.Jar,		name:'識別の壺',			price:{buy:600,		sell:210} },
	{ type:ItemType.Jar,		name:'やりすごしの壺',		price:{buy:600,		sell:210} },
	{ type:ItemType.Jar,		name:'四二鉢',				price:{buy:600,		sell:210} },
	{ type:ItemType.Jar,		name:'ただの壺',			price:{buy:600,		sell:210} },
	{ type:ItemType.Jar,		name:'換金の壺',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Jar,		name:'変化の壺',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Jar,		name:'手封じの壺',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Jar,		name:'割れない壺',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Jar,		name:'水がめ',				price:{buy:1000,	sell:350} },
	{ type:ItemType.Jar,		name:'油壺',				price:{buy:1000,	sell:350} },
	{ type:ItemType.Jar,		name:'チョコの壺',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Jar,		name:'おはらいの壺',		price:{buy:1600,	sell:560} },
	{ type:ItemType.Jar,		name:'たたりの壺',			price:{buy:1600,	sell:560} },
	{ type:ItemType.Jar,		name:'祝福の壺',			price:{buy:1600,	sell:560} },
	{ type:ItemType.Jar,		name:'蔵の壺',				price:{buy:2500,	sell:875} },
	{ type:ItemType.Jar,		name:'底抜けの壺',			price:{buy:2500,	sell:875} },
	{ type:ItemType.Jar,		name:'背中の壺',			price:{buy:3800,	sell:1330} },
	{ type:ItemType.Jar,		name:'トドの壺',			price:{buy:3800,	sell:1330} },
	{ type:ItemType.Jar,		name:'魔物の壺',			price:{buy:3800,	sell:1330} },
	{ type:ItemType.Jar,		name:'呼び出しの壺',		price:{buy:3800,	sell:1330} },
	{ type:ItemType.Jar,		name:'合成の壺',			price:{buy:6000,	sell:2100} },
	{ type:ItemType.Jar,		name:'強化の壺',			price:{buy:10000,	sell:3500} },
	{ type:ItemType.Jar,		name:'弱化の壺',			price:{buy:10000,	sell:3500} },
	// 杖
	{ type:ItemType.Cane,		name:'吹き飛ばしの杖',		price:{buy:1000,	sell:350} },
	{ type:ItemType.Cane,		name:'場所がえの杖',		price:{buy:1000,	sell:350} },
	{ type:ItemType.Cane,		name:'雷光の杖',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Cane,		name:'飛びつきの杖',		price:{buy:1000,	sell:350} },
	{ type:ItemType.Cane,		name:'加速の杖',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Cane,		name:'鈍足の杖',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Cane,		name:'魔道の杖',			price:{buy:1000,	sell:350} },
	{ type:ItemType.Cane,		name:'かなしばりの杖',		price:{buy:1500,	sell:525} },
	{ type:ItemType.Cane,		name:'一時しのぎの杖',		price:{buy:1500,	sell:525} },
	{ type:ItemType.Cane,		name:'痛み分けの杖',		price:{buy:1500,	sell:525} },
	{ type:ItemType.Cane,		name:'転ばぬ先の杖',		price:{buy:1500,	sell:525} },
	{ type:ItemType.Cane,		name:'ワナ消しの杖',		price:{buy:1500,	sell:525} },
	{ type:ItemType.Cane,		name:'ただの杖',			price:{buy:1500,	sell:525} },
	{ type:ItemType.Cane,		name:'封印の杖',			price:{buy:2000,	sell:700} },
	{ type:ItemType.Cane,		name:'身代わりの杖',		price:{buy:2000,	sell:700} },
	{ type:ItemType.Cane,		name:'トンネルの杖',		price:{buy:3000,	sell:1050} },
	{ type:ItemType.Cane,		name:'土塊の杖',			price:{buy:3000,	sell:1050} },
	{ type:ItemType.Cane,		name:'幸せの杖',			price:{buy:4000,	sell:1400} },
	{ type:ItemType.Cane,		name:'不幸の杖',			price:{buy:4000,	sell:1400} },
]


